version: "3.8"

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_CONT_NAME}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ${MONGO_VOLUME}:/data/db



volumes:
  mongo_data:
